version: '3.3'
services: 
    flask-backend:
        build: 
            context: ../BA-Backend/
            network: host
    
    flask-services:
        build:
            context: ../BA-Services/
            network: host
    frontend:
        build:
            context: ../BA-Frontend/
            network: host