version: '3.3'
services:       
    rabbitmq:
        ports: 
            - "4369:4369"
            - "5671:5671"
            - "5672:5672"
            - "25672:25672"
            - "15671:15671"
            - "15672:15672"
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:15672"]
            interval: 30s
            timeout: 10s
            retries: 5
        image: rabbitmq:latest
        networks:
            - custom-network
        
    redis: 
        ports: 
            - '6379:6379'
        image: redis:latest
        networks:
            - custom-network
            
    mysql: 
        ports: 
            - '3333:3306'
        volumes: 
            - mysql-conf:/etc/mysql/conf.d
            - mysql-storage:/var/lib/mysql
            - ./setup.sql:/docker-entrypoint-initdb.d/init.sql:r
        restart: on-failure
        environment: 
            MYSQL_ROOT_PASSWORD: admin
        image: mysql:latest
        networks:
            - custom-network
        
    flask-backend:
        ports: 
            - '5000:80'
        image: ba-docker-flask-backend
        restart: on-failure
        depends_on: 
            - redis
            - mysql
            - rabbitmq
        environment:
            - REDIS_HOST=redis
            - RABBIT_HOST=rabbitmq
            - MYSQL_HOST=mysql
            - MYSQL_PORT=3306
            - JWT_PASSWORD=e8tzvw-tH!DFGsg9
        networks:
            - custom-network
                   
    grafana:
        ports:
            - '3000:3000'
        restart: on-failure
        depends_on: 
            - mysql
        volumes:
            - grafana-storage:/var/lib/grafana
        image: grafana/grafana:latest
        user: "472"
        networks:
            - custom-network
            
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
        container_name: elasticsearch
        environment:
            xpack.security.enabled: "false"
            discovery.type: single-node
            ES_JAVA_OPTS: -Xms750m -Xmx750m
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536
                hard: 65536
        cap_add:
            - IPC_LOCK
        volumes:
            - elasticsearch-data:/usr/share/elasticsearch/data
        ports:
            - 9200:9200
            - 9300:9300
        networks:
            - custom-network
            
    frontend:
        image: ba-docker-frontend
        ports:
            - 4200:4200
        command: >
            bash -c "npm install && ng serve --host 0.0.0.0 --port 4200"
            
networks: 
    custom-network:
        driver: bridge
        name: custom-network
        
volumes:
  grafana-storage:
  mysql-storage:
  mysql-conf:
  elasticsearch-data:
    driver: local