version: '3.3'
services:       
    mysql: 
        ports: 
            - '3333:3306'
        volumes: 
            - mysql-conf:/etc/mysql/conf.d
            - mysql-storage:/var/lib/mysql
            - setup.sql:/docker-entrypoint-initdb.d/init.sql:ro
        restart: on-failure
        environment: 
            MYSQL_ROOT_PASSWORD: admin
        image: mysql:latest
        networks:
            - custom-network

networks: 
    custom-network:
        driver: bridge
        name: custom-network
        
volumes:
  mysql-storage:
  mysql-conf:
  